-- Your SQL goes here
ALTER TABLE users ALTER COLUMN first_name DROP NOT NULL;
ALTER TABLE users ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ALTER COLUMN is_superuser SET DEFAULT FALSE;
ALTER TABLE users ALTER COLUMN is_staff SET DEFAULT FALSE;
ALTER TABLE users ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE users ALTER COLUMN date_joined SET DEFAULT CURRENT_TIMESTAMP;