# syntax=docker/dockerfile:1

# Use the latest Bun image
FROM oven/bun:latest

# Set a working directory
WORKDIR /app

# Copy package files
COPY package*.json ./
COPY bun.lockb ./bun.lock

RUN bun install

COPY . .

# Expose the port used by your app (adjust if needed)
EXPOSE 3000

# Command to run the development server
CMD ["bun", "run", "dev"]