# syntax=docker/dockerfile:1

# Use the latest Bun image
FROM oven/bun:latest

# Set a working directory
WORKDIR /app

# Copy package files
COPY package*.json ./
COPY bun.lockb ./bun.lock

RUN bun install
RUN bun install -g nodemon chokidar

COPY . .

# Expose the port used by your app (adjust if needed)
EXPOSE 3000

# Set environment variable and run the development server
ENV ORIGIN="https://next-precisely-piranha.ngrok-free.app"
CMD ["bun", "run", "dev"]