name: fl-build

services:
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile
      args:
        RUSTFLAGS: "-C target-cpu=native"
