services:
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile.dev
    container_name: svelte-fl
    ports:
      - "5173:3000"
    volumes:
      - ./svelte:/app
    env_file:
      - ./svelte/.env
    depends_on:
      - axum

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile.dev
    container_name: axum-fl
    ports:
      - "8000:8000"
    volumes:
      - ./axum:/app
      - cargo-cache:/usr/local/cargo/registry
    env_file:
      - ./axum/.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: pg-fl-dev
    restart: always
    user: postgres
    volumes:
      - pg-fl-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD} # Use environment variable for security
    ports:
      - "5432:5432" # Keep this port mapping for admin access or debugging
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cargo-cache:
  pg-fl-dev:
