name: ogonek-build
services:
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile
      platforms: ["linux/amd64"]
      tags:
        - ${SVELTE_IMAGE}
    image: ${SVELTE_IMAGE}

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile
      platforms: ["linux/amd64"]
      cache_from:
        - ${AXUM_IMAGE}
      target: builder
    image: ${AXUM_IMAGE}
