services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-firelight
    ports:
      - "3100:3000" 
    volumes:
      - ./frontend:/app

    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:8000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-firelight
    ports:
      - "8002:8000" # Different external port for backend
    volumes:
      - ./backend:/app
      - media-volume-2:/app/media
    env_file:
      - ./backend/.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  redis:
    image: redis/redis-stack:latest
    container_name: redis-firelight-rust
    ports:
      - "6379:6379"
      - "8003:8001"

