name: fl-build

services:
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile
    env_file:
      - ./svelte/.env.production

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile
      args:
        RUSTFLAGS: "-C target-cpu=native"
    env_file:
      - ./axum/.env.production

  upld:
    build:
      context: ./upload-service
      dockerfile: Dockerfile
    env_file:
      - ./upload-service/.env
