name: ogonek-staging

services:
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile
    container_name: svelte-ogonek-staging
    env_file:
      - ./svelte/.env
    ports:
      - "3333:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-ogonek-staging

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile
    container_name: axum-ogonek-staging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./axum/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
  postgres:
    image: postgres
    container_name: pg-ogonek-staging
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pg-ogonek-staging
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
    name: db-ogonek-staging
