# this builds our mighty containers
services:
  traefik:
    container_name: trfk-prod
    image: traefik:v3.3
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "127.0.0.1:3333:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    restart: unless-stopped

  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile
    container_name: svelte-fl-prod
    env_file:
      - ./svelte/.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svelte.rule=Host(`localhost`)"
    networks:
      - web
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile
      args:
        RUSTFLAGS: "-C target-cpu=native"
    container_name: axum-fl-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./axum/.env.production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - cargo-cache:/usr/local/cargo/registry:cached
      - cargo-target:/app/target:cached
    networks:
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:17-alpine
    container_name: pg-fl-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  db-data:
    name: db-fl-prod
  cargo-cache:
    name: cargo-cache-fl-prod
  cargo-target:
    name: cargo-target-fl-prod

networks:
  web:
    name: web
  internal:
    name: internal
    internal: true
