services:
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile.dev
    container_name: svelte-fl-dev
    ports:
      - "5173:5173"
    volumes:
      - ./svelte:/app
      - uploads:/app/public/media
    env_file:
      - ./svelte/.env
    depends_on:
      - axum


  nginx:
    image: nginx
    container_name: nginx-fl-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/app/public/media:ro  # assuming these are static files
    depends_on:
      - svelte
      - axum

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile.dev
    container_name: axum-fl-dev
    volumes:
      - ./axum:/app
      - cargo-cache:/usr/local/cargo/registry
      - cargo-target:/app/target
    env_file:
      - ./axum/.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: pg-fl-dev
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cargo-cache:
    name: cargo-cache-fl-dev
  cargo-target:
    name: cargo-target-fl-dev
  db-data:
    name: db-fl-data
  uploads:
    name: uploads-fl-dev