services:
  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"  # For dev only - gives you the dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile.dev
    container_name: svelte-fl-dev
    volumes:
      - ./svelte:/app
      - uploads:/app/public/media
    env_file:
      - ./svelte/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svelte.rule=Host(`localhost`)"
      - "traefik.http.services.svelte.loadbalancer.server.port=5173"
    depends_on:
      - axum
    
  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile.dev
    container_name: axum-fl-dev
    volumes:
      - ./axum:/app
      - cargo-cache:/usr/local/cargo/registry
      - cargo-target:/app/target
    env_file:
      - ./axum/.env

    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.axum.rule=Host(`localhost`) && PathPrefix(`/axum`)"
      - "traefik.http.services.axum.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.axum-strip.stripprefix.prefixes=/axum"
      - "traefik.http.routers.axum.middlewares=axum-strip"

  postgres:
    image: postgres
    container_name: pg-fl-dev
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cargo-cache:
    name: cargo-cache-fl-dev
  cargo-target:
    name: cargo-target-fl-dev
  db-data:
    name: db-fl-data
  uploads:
    name: uploads-fl-dev

networks:
  host:
    external: true