services:
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile
    container_name: svelte-fl-prod
    env_file:
      - ./svelte/.env.production
    ports:
      - "3333:3000"
    networks:
      - web
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile
      args:
        RUSTFLAGS: "-C target-cpu=native"
    container_name: axum-fl-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./axum/.env.production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - cargo-cache:/usr/local/cargo/registry:cached
      - cargo-target:/app/target:cached
    networks:
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  postgres:
    image: postgres:17-alpine
    container_name: pg-fl-prod
    restart: unless-stopped
    env_file: ./.env.production
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  db-data:
    name: db-fl-prod
  cargo-cache:
    name: cargo-cache-fl-prod
  cargo-target:
    name: cargo-target-fl-prod

networks:
  web:
    name: web
  internal:
    name: internal
    internal: true
