services:
  svelte:
    image: ghcr.io/noxlovette/fl-prod-svelte:v1.0.5
    container_name: svelte-fl-prod
    env_file:
      - ./.env.svelte
    ports:
      - "3333:3000"
    networks:
      - web
      - internal
    restart: unless-stopped
    volumes:
      - uploads:/app/static/uploads
    user: nodejs:nodejs
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy

  axum:
    image: ghcr.io/noxlovette/fl-prod-axum:v1.0.3
    container_name: axum-fl-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./.env.axum
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  media:
    image: nginx:alpine
    ports: 
      - "8888:80"
    container_name: media-fl-prod
    volumes:
      - uploads:/var/www/uploads
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped


  postgres:
    image: postgres:17-alpine
    container_name: pg-fl-prod
    restart: unless-stopped
    env_file: ./.env.postgres
    ports:
      - "5444:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  db-data:
    name: db-fl-prod
  uploads:
    name: uploads-fl-prod

networks:
  web:
    name: web-fl
  internal:
    name: internal-fl
    internal: true
