services:
  svelte:
    image: ghcr.io/noxlovette/fl-prod-svelte:latest
    container_name: svelte-fl-prod
    env_file:
      - ./.env.svelte
    ports:
      - "3333:3000"
    networks:
      - web
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy

  axum:
    image: ghcr.io/noxlovette/fl-prod-axum:latest
    container_name: axum-fl-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./.env.axum
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  upld:
    image: ghcr.io/noxlovette/fl-prod-upld:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: upld-fl-prod
    volumes:
      - uploads:/app/uploads
    env_file:
      - ./upld.env

  postgres:
    image: postgres:17-alpine
    container_name: pg-fl-prod
    restart: unless-stopped
    env_file: ./.env.postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  db-data:
    name: db-fl-prod
  uploads:
    name: uploads-fl-prod

networks:
  web:
    name: web-fl
  internal:
    name: internal-fl
    internal: true
