services:
  caddy:
    image: caddy:latest
    restart: unless-stopped 
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  
    volumes:
      - uploads:/srv/uploads
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/caddy-data:/data
      - ./caddy/caddy-config:/config
    depends_on:
      - svelte
      - axum

  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile.dev
    container_name: svelte-fl-dev
    volumes:
      - ./svelte/src:/app/src
      - ./svelte/static:/app/static
      - ./svelte/.svelte-kit:/app/.svelte-kit
      - ./svelte/public:/app/public
      - ./svelte/tailwind.config.js/:/app/tailwind.config.js
      - uploads:/app/uploads
    env_file:
      - ./svelte/.env
    depends_on:
      - axum

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile.dev
    container_name: axum-fl-dev
    volumes:
      - ./axum:/app
      - cargo-cache:/usr/local/cargo/registry
      - cargo-target:/app/target
    env_file:
      - ./axum/.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: pg-fl-dev
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pg-fl-dev
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cargo-cache:
    name: cargo-cache-fl-dev
  cargo-target:
    name: cargo-target-fl-dev
  db-data:
    name: db-fl-data
  uploads:
    name: uploads-fl-dev
  caddy-data:
    name: caddy-fl-dev