# syntax=docker/dockerfile:1

# Use the official Python image.
ARG PYTHON_VERSION=3.12.3
FROM python:${PYTHON_VERSION}

# Prevent Python from writing pyc files and buffering stdout and stderr.
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory.
WORKDIR /app

# Install system dependencies including compilers.
RUN apt-get update && apt-get install -y gcc python3-dev

# Install Python dependencies.
COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt

# Copy the project files into the container.
COPY . .

# Expose the port for the development server.
EXPOSE 8000

# Command to run the development server.
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
