[package]
name = "rust"
version = "1.1.5"
edition = "2021"


[dependencies]
# Primary Crates
axum = { version = "0.8.1", features = ["macros", "multipart"] }
axum-extra = { version = "0.10.0", features = ["typed-header", "cookie"] }
sqlx = { version = "0.8.2", features = [
    "runtime-tokio",
    "tls-rustls-ring",
    "postgres",
    "time",
    "uuid",
    "chrono",
] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
bytes = "1.4"

# Secondary Crates
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "2.0.0", features = ["time_0_3"] }
jsonwebtoken = { version = "9.3.0", features = ["use_pem"] }
log = "0.4"
uuid = { version = "1.11.0", features = ["serde", "v4", "v7"] }
hyper = "1.5.2"
argon2 = "0.5.3"


# Auxiliary Crates
thiserror = "2.0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.6.2", features = ["full"] }
anyhow = "1.0.95"
validator = { version = "0.19.0", features = ["derive"] }
dotenvy = "0.15"
once_cell = "1.20.2"
regex = "1.11.1"
nanoid = "0.4.0"
time = "0.3.37"
tower = { version = "0.5.2", features = ["full"] }
base64 = "0.22.1"
csv = "1.3.1"
mime_guess = "2.0.5"
aws-sdk-s3 = "1.79.0"
aws-credential-types = "1.2.2"
aws-config = "1.6.0"
futures-util = "0.3.31"
