[package]
name = "ogonek"
version = "1.7.4"
edition = "2024"


[dependencies]
# Primary Crates
axum = { version = "0.8.1", features = ["macros", "multipart"] }
axum-extra = { version = "0.10.0", features = ["typed-header", "cookie"] }
sqlx = { version = "0.8.2", features = [
    "runtime-tokio",
    "tls-rustls-ring",
    "postgres",
    "uuid",
    "migrate",
    "chrono"] }
tokio = { version = "1.47", features = ["full"] }

# Secondary Crates
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.142"
jsonwebtoken = { version = "9.3.0", features = ["use_pem"] }
argon2 = "0.5.3"

# Auxiliary Crates
thiserror = "2.0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tower-http = { version = "0.6.2", features = ["full"] }
anyhow = "1.0.95"
validator = { version = "0.20.0", features = ["derive"] }
dotenvy = "0.15"
nanoid = "0.4.0"
base64 = "0.22.1"
aws-sdk-s3 = "1.100.0"
aws-credential-types = "1.2.2"
aws-config = "1.6.0"
sentry = {version ="0.41", features = ["tracing"]}
atty = "0.2.14"
sentry-tower = {version = "0.38.1", features = ["axum", "axum-matched-path", "http"]}
utoipa = {version ="5.4.0", features = ["chrono"]}
utoipa-axum = {version ="0.2.0"}
serde_yaml = "0.9.34"
reqwest = "0.12.23"
tokio-util = "0.7.16"
a2 = "0.10.0"
