FROM rust:latest
WORKDIR /app

RUN apt-get update && apt-get install -y pkg-config libssl-dev
RUN cargo install sqlx-cli --no-default-features --features postgres

CMD ["cargo", "run", "--bin", "rust"]