max_width = 100
tab_spaces = 4
edition = "2024"
merge_derives = true
use_field_init_shorthand = true
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true