# Generated by Django 5.1.3 on 2024-11-05 19:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Markdown and LaTeX raw content')),
                ('processed_html', models.TextField(help_text='HTML content processed from markdown and LaTeX')),
            ],
        ),
    ]
