# Generated by Django 5.1.3 on 2024-11-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_concept_tag_article_related_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='URL friendly title', max_length=255, null=True, unique=True),
        ),
    ]
