# Generated by Django 5.1.4 on 2024-12-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_description_task_content_remove_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quizlet_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
