# Generated by Django 5.1.4 on 2024-12-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_lessons_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
