# Generated by Django 5.1.4 on 2024-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_lesson_delete_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='manual_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
