# Generated by Django 5.1.4 on 2024-12-17 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
