-- Your SQL goes here
CREATE TABLE lessons (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category VARCHAR(50) NOT NULL DEFAULT 'grammar',
    topic VARCHAR(50) NOT NULL DEFAULT 'english',
    manual_date TIMESTAMP WITH TIME ZONE,
    bookmarked BOOLEAN NOT NULL DEFAULT FALSE,
    assignee_id UUID NOT NULL,
    FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE CASCADE
);