[package]
name = "ogonek_s3"
version = "0.1.0"
edition = "2024"

[dependencies]
ogonek_types = { path = "../ogonek-types" }
aws-sdk-s3 = "1.105.0"
aws-credential-types = "1.2.6"
aws-config = "1.8.6"

anyhow.workspace = true
tracing.workspace = true
axum.workspace = true
thiserror.workspace = true