# syntax=docker/dockerfile:1

FROM node:24.7.0-slim 

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

# Set environment variables for Vite in Docker
ENV CI=true
ENV VITE_CJS_IGNORE_WARNING=true

COPY pnpm-lock.yaml package.json ./

RUN pnpm install --frozen-lockfile

RUN pnpm add -g nodemon chokidar

COPY . .

EXPOSE 5173

CMD ["pnpm", "run", "dev"]