name: ogonek-build
services:
  svelte:
    platform: linux/amd64
    build:
      context: ../svelte
      dockerfile: Dockerfile
      tags:
        - ${SVELTE_IMAGE}
    image: ${SVELTE_IMAGE}
  axum:
    platform: linux/amd64
    build:
      context: ../axum
      dockerfile: Dockerfile
      tags:
        - ${AXUM_IMAGE}
    image: ${AXUM_IMAGE}
