

[package]
name = "rust"
version = "0.1.0"
edition = "2021"


[dependencies]
diesel = { version = "2.2.6", features = ["postgres", "chrono", "r2d2", "uuid"] }
# build libpq and openssl as part of the build process
# uncomment these lines if you run into setup issues
# pq-sys = { version = "0.6", features = ["bundled"] }
# openssl-sys = { version = "0.9.100", features = ["vendored"] } 
dotenvy = "0.15"
chrono = { version = "0.4", features = ["serde"] }
r2d2 = "0.8.10"
uuid = { version = "1.11.0", features = ["serde", "v4"] }
bcrypt = '0.16'
ulid = '1.1.3'
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "9.3.0"  # Check for the latest version
serde_json = "1.0"
actix-web = "4.0"
env_logger =  "0.11.6"
log4rs = '1.3.0'
log = "0.4"