

[package]
name = "rust"
version = "0.1.0"
edition = "2021"


[dependencies]
diesel = { version = "2.2.6", features = ["postgres", "chrono", "r2d2", "uuid"] }
# build libpq and openssl as part of the build process
# uncomment these lines if you run into setup issues
# pq-sys = { version = "0.6", features = ["bundled"] }
# openssl-sys = { version = "0.9.100", features = ["vendored"] } 
dotenvy = "0.15"
chrono = "0.4"
r2d2 = "0.8.8"
uuid = { version = "1.11.0", features = ["serde", "v4"] }
bcrypt = '0.16'
ulid = '0.4'
