[package]
name = "ogonek_types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true

validator = { version = "0.20.0", features = ["derive"] }
anyhow.workspace = true
chrono.workspace = true
utoipa.workspace = true