import { env } from "$env/dynamic/private";
import { createApi } from "unsplash-js";
import type { Basic } from "unsplash-js/dist/methods/photos/types";

const serverApi = createApi({
  accessKey: env.UNSPLASH_ACCESS_KEY,
});

export { serverApi as unsplash };

export const mock: Basic[] = [
  {
    id: "OxK32aLJXWU",
    created_at: "2018-08-02T02:41:47Z",
    updated_at: "2025-09-05T06:13:04Z",
    promoted_at: null,
    width: 4000,
    height: 2672,
    color: "#a6c00c",
    blur_hash: "LBJI#{^zyNTsy#-7I=rsGiteVgQ?",
    description: "Zaroślarka pospolita",
    alt_description: "selective focus photography of snail on plant",
    urls: {
      raw: "https://images.unsplash.com/photo-1533177243638-dd485701f717?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1533177243638-dd485701f717?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1533177243638-dd485701f717?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1533177243638-dd485701f717?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1533177243638-dd485701f717?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=200",
    },
    links: {
      self: "https://api.unsplash.com/photos/selective-focus-photography-of-snail-on-plant-OxK32aLJXWU",
      html: "https://unsplash.com/photos/selective-focus-photography-of-snail-on-plant-OxK32aLJXWU",
      download:
        "https://unsplash.com/photos/OxK32aLJXWU/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
      download_location:
        "https://api.unsplash.com/photos/OxK32aLJXWU/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
    },
    user: {
      id: "kzc2j2nnJRM",
      updated_at: "2025-09-04T09:42:51Z",
      username: "zmachacek",
      name: "Zdeněk Macháček",
      first_name: "Zdeněk",
      last_name: "Macháček",
      twitter_username: null,
      portfolio_url: "https://zephotos.smugmug.com/",
      bio: "Nature photographer based in Czech Republic",
      location: "Czech Republic",
      instagram_username: "zmachacek6710",
      total_collections: 13,
      total_likes: 103,
      total_photos: 1329,
      links: {},
      profile_image: { small: "hi", large: "hi", medium: "hi" },
    },
    likes: 293,
  },
  {
    id: "_9bRrDyOQTQ",
    slug: "brown-snail-on-rock-_9bRrDyOQTQ",
    alternative_slugs: {
      en: "brown-snail-on-rock-_9bRrDyOQTQ",
      es: "caracol-marron-en-la-roca-_9bRrDyOQTQ",
      ja: "岩の上の茶色のカタツムリ-_9bRrDyOQTQ",
      fr: "escargot-brun-sur-rocher-_9bRrDyOQTQ",
      it: "lumaca-marrone-su-roccia-_9bRrDyOQTQ",
      ko: "바위에-갈색-달팽이-_9bRrDyOQTQ",
      de: "braune-schnecke-auf-felsen-_9bRrDyOQTQ",
      pt: "caracol-marrom-na-rocha-_9bRrDyOQTQ",
      id: "siput-coklat-di-atas-batu-_9bRrDyOQTQ",
    },
    created_at: "2019-08-30T10:36:34Z",
    updated_at: "2025-09-05T09:13:06Z",
    promoted_at: null,
    width: 5763,
    height: 3953,
    color: "#a68c73",
    blur_hash: "LIHw.B%1-p-p0yIpNGxZI.jtE1Ip",
    description: null,
    alt_description: "brown snail on rock",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1567161291513-d8d58620c5ca?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1567161291513-d8d58620c5ca?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1567161291513-d8d58620c5ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1567161291513-d8d58620c5ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1567161291513-d8d58620c5ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1567161291513-d8d58620c5ca",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-snail-on-rock-_9bRrDyOQTQ",
      html: "https://unsplash.com/photos/brown-snail-on-rock-_9bRrDyOQTQ",
      download:
        "https://unsplash.com/photos/_9bRrDyOQTQ/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
      download_location:
        "https://api.unsplash.com/photos/_9bRrDyOQTQ/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
    },
    likes: 174,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "kzc2j2nnJRM",
      updated_at: "2025-09-04T09:42:51Z",
      username: "zmachacek",
      name: "Zdeněk Macháček",
      first_name: "Zdeněk",
      last_name: "Macháček",
      twitter_username: null,
      portfolio_url: "https://zephotos.smugmug.com/",
      bio: "Nature photographer based in Czech Republic",
      location: "Czech Republic",
      links: [Object],
      profile_image: [Object],
      instagram_username: "zmachacek6710",
      total_collections: 13,
      total_likes: 103,
      total_photos: 1329,
      total_promoted_photos: 190,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: [Object],
    },
  },
  {
    id: "5TEN19lBTBI",
    slug: "brown-snail-on-green-grass-during-daytime-5TEN19lBTBI",
    alternative_slugs: {
      en: "brown-snail-on-green-grass-during-daytime-5TEN19lBTBI",
      es: "caracol-marron-en-hierba-verde-durante-el-dia-5TEN19lBTBI",
      ja: "昼間の緑の草の上にいる茶色のカタツムリ-5TEN19lBTBI",
      fr: "escargot-brun-sur-lherbe-verte-pendant-la-journee-5TEN19lBTBI",
      it: "lumaca-marrone-su-erba-verde-durante-il-giorno-5TEN19lBTBI",
      ko: "낮-동안-푸른-풀밭에-갈색-달팽이-5TEN19lBTBI",
      de: "braune-schnecke-tagsuber-auf-grunem-gras-5TEN19lBTBI",
      pt: "caracol-marrom-na-grama-verde-durante-o-dia-5TEN19lBTBI",
      id: "siput-coklat-di-rumput-hijau-di-siang-hari-5TEN19lBTBI",
    },
    created_at: "2020-01-19T22:08:59Z",
    updated_at: "2025-09-05T06:59:00Z",
    promoted_at: null,
    width: 4929,
    height: 3418,
    color: "#f3f3f3",
    blur_hash: "L:He%qofR%WB~qj[jufQ-;fjoMoL",
    description: null,
    alt_description: "brown snail on green grass during daytime",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1579470785623-3d2c229f4fc6?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1579470785623-3d2c229f4fc6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1579470785623-3d2c229f4fc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1579470785623-3d2c229f4fc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1579470785623-3d2c229f4fc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1579470785623-3d2c229f4fc6",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-snail-on-green-grass-during-daytime-5TEN19lBTBI",
      html: "https://unsplash.com/photos/brown-snail-on-green-grass-during-daytime-5TEN19lBTBI",
      download:
        "https://unsplash.com/photos/5TEN19lBTBI/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
      download_location:
        "https://api.unsplash.com/photos/5TEN19lBTBI/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
    },
    likes: 156,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: [Object],
      wallpapers: [Object],
      sustainability: [Object],
    },
    asset_type: "photo",
    user: {
      id: "aZaCovM9xLk",
      updated_at: "2025-02-06T06:47:49Z",
      username: "amir_v_ali",
      name: "amirali mirhashemian",
      first_name: "amirali",
      last_name: "mirhashemian",
      twitter_username: null,
      portfolio_url: "http://amiralimir.com",
      bio: "follow my Instagram: @amirali_does_stuff",
      location: null,
      links: [Object],
      profile_image: [Object],
      instagram_username: "amirali_does_stuff",
      total_collections: 0,
      total_likes: 56,
      total_photos: 166,
      total_promoted_photos: 3,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: [Object],
    },
  },
  {
    id: "Gj0YV3V-OsQ",
    slug: "brown-snail-on-green-fruit-Gj0YV3V-OsQ",
    alternative_slugs: {
      en: "brown-snail-on-green-fruit-Gj0YV3V-OsQ",
      es: "caracol-marron-sobre-fruta-verde-Gj0YV3V-OsQ",
      ja: "緑の果実に茶色のカタツムリ-Gj0YV3V-OsQ",
      fr: "escargot-brun-sur-fruit-vert-Gj0YV3V-OsQ",
      it: "lumaca-marrone-su-frutto-verde-Gj0YV3V-OsQ",
      ko: "녹색-과일에-갈색-달팽이-Gj0YV3V-OsQ",
      de: "braune-schnecke-auf-grunen-fruchten-Gj0YV3V-OsQ",
      pt: "caracol-marrom-na-fruta-verde-Gj0YV3V-OsQ",
      id: "siput-coklat-pada-buah-hijau-Gj0YV3V-OsQ",
    },
    created_at: "2018-09-14T02:19:06Z",
    updated_at: "2025-09-05T07:14:09Z",
    promoted_at: null,
    width: 4000,
    height: 2672,
    color: "#f3f38c",
    blur_hash: "L?L:u80OWYxX%1i{M}s.R+t6RRkC",
    description: "Nastrojowe zdjęcie mięczaka",
    alt_description: "brown snail on green fruit",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1536891361854-3cd6e0809384?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1536891361854-3cd6e0809384?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1536891361854-3cd6e0809384?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1536891361854-3cd6e0809384?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1536891361854-3cd6e0809384?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1536891361854-3cd6e0809384",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-snail-on-green-fruit-Gj0YV3V-OsQ",
      html: "https://unsplash.com/photos/brown-snail-on-green-fruit-Gj0YV3V-OsQ",
      download:
        "https://unsplash.com/photos/Gj0YV3V-OsQ/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
      download_location:
        "https://api.unsplash.com/photos/Gj0YV3V-OsQ/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
    },
    likes: 74,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: { animals: [Object] },
    asset_type: "photo",
    user: {
      id: "enz98pYfOsc",
      updated_at: "2024-10-29T02:16:33Z",
      username: "epan5",
      name: "Krzysztof  Niewolny",
      first_name: "Krzysztof",
      last_name: "Niewolny",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location:
        "Grudziądz, Polska, Województwo kujawsko-pomorskie, Osiedle Lotnisko",
      links: [Object],
      profile_image: [Object],
      instagram_username: null,
      total_collections: 6,
      total_likes: 293,
      total_photos: 1942,
      total_promoted_photos: 13,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: [Object],
    },
  },
  {
    id: "wkKipnLHbKE",
    slug: "a-snail-that-is-sitting-on-a-leaf-wkKipnLHbKE",
    alternative_slugs: {
      en: "a-snail-that-is-sitting-on-a-leaf-wkKipnLHbKE",
      es: "un-caracol-que-esta-sentado-en-una-hoja-wkKipnLHbKE",
      ja: "葉の上に座っているカタツムリ-wkKipnLHbKE",
      fr: "un-escargot-assis-sur-une-feuille-wkKipnLHbKE",
      it: "una-lumaca-che-e-seduta-su-una-foglia-wkKipnLHbKE",
      ko: "나뭇잎-위에-앉아있는-달팽이-wkKipnLHbKE",
      de: "eine-schnecke-die-auf-einem-blatt-sitzt-wkKipnLHbKE",
      pt: "um-caracol-que-esta-sentado-em-uma-folha-wkKipnLHbKE",
      id: "siput-yang-duduk-di-atas-daun-wkKipnLHbKE",
    },
    created_at: "2023-09-28T12:17:20Z",
    updated_at: "2025-09-05T09:48:57Z",
    promoted_at: null,
    width: 5184,
    height: 3456,
    color: "#405940",
    blur_hash: "L698Fw%y9aMzDRRRM#RQ02RQ$*ti",
    description: null,
    alt_description: "a snail that is sitting on a leaf",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1695903431964-23ba338ee1e8?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1695903431964-23ba338ee1e8?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1695903431964-23ba338ee1e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1695903431964-23ba338ee1e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1695903431964-23ba338ee1e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1695903431964-23ba338ee1e8",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-snail-that-is-sitting-on-a-leaf-wkKipnLHbKE",
      html: "https://unsplash.com/photos/a-snail-that-is-sitting-on-a-leaf-wkKipnLHbKE",
      download:
        "https://unsplash.com/photos/wkKipnLHbKE/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
      download_location:
        "https://api.unsplash.com/photos/wkKipnLHbKE/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
    },
    likes: 10,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: { nature: [Object] },
    asset_type: "photo",
    user: {
      id: "O6EG2HI9HCQ",
      updated_at: "2025-08-13T01:19:25Z",
      username: "taylorllc",
      name: "t",
      first_name: "t",
      last_name: null,
      twitter_username: null,
      portfolio_url: null,
      bio: "photographer, designer, curator, collector",
      location: null,
      links: [Object],
      profile_image: [Object],
      instagram_username: "taylorllc",
      total_collections: 2,
      total_likes: 7,
      total_photos: 53,
      total_promoted_photos: 0,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: [Object],
    },
  },
  {
    id: "_-6EW6wcY8Q",
    slug: "ladybug-on-yellow-snail-_-6EW6wcY8Q",
    alternative_slugs: {
      en: "ladybug-on-yellow-snail-_-6EW6wcY8Q",
      es: "mariquita-en-caracol-amarillo-_-6EW6wcY8Q",
      ja: "黄色いカタツムリのてんとう虫-_-6EW6wcY8Q",
      fr: "coccinelle-sur-escargot-jaune-_-6EW6wcY8Q",
      it: "coccinella-su-lumaca-gialla-_-6EW6wcY8Q",
      ko: "노란-달팽이에-무당벌레-_-6EW6wcY8Q",
      de: "marienkafer-auf-gelber-schnecke-_-6EW6wcY8Q",
      pt: "joaninha-no-caracol-amarelo-_-6EW6wcY8Q",
      id: "kepik-pada-siput-kuning-_-6EW6wcY8Q",
    },
    created_at: "2018-11-11T15:02:36Z",
    updated_at: "2025-09-05T07:20:31Z",
    promoted_at: null,
    width: 3845,
    height: 2524,
    color: "#f3d90c",
    blur_hash: "LLQ8BY%c?:w{yOtxs9Rl~j-+9hM*",
    description: "Wstężyk gajowy i biedronka siedmiokropka",
    alt_description: "ladybug on yellow snail",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1541948342185-4ecd95854025?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1541948342185-4ecd95854025?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1541948342185-4ecd95854025?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1541948342185-4ecd95854025?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1541948342185-4ecd95854025?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1541948342185-4ecd95854025",
    },
    links: {
      self: "https://api.unsplash.com/photos/ladybug-on-yellow-snail-_-6EW6wcY8Q",
      html: "https://unsplash.com/photos/ladybug-on-yellow-snail-_-6EW6wcY8Q",
      download:
        "https://unsplash.com/photos/_-6EW6wcY8Q/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
      download_location:
        "https://api.unsplash.com/photos/_-6EW6wcY8Q/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
    },
    likes: 117,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "enz98pYfOsc",
      updated_at: "2024-10-29T02:16:33Z",
      username: "epan5",
      name: "Krzysztof  Niewolny",
      first_name: "Krzysztof",
      last_name: "Niewolny",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location:
        "Grudziądz, Polska, Województwo kujawsko-pomorskie, Osiedle Lotnisko",
      links: [Object],
      profile_image: [Object],
      instagram_username: null,
      total_collections: 6,
      total_likes: 293,
      total_photos: 1942,
      total_promoted_photos: 13,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: [Object],
    },
  },
  {
    id: "oKhcGwGcENQ",
    slug: "brown-snail-on-green-leaf-oKhcGwGcENQ",
    alternative_slugs: {
      en: "brown-snail-on-green-leaf-oKhcGwGcENQ",
      es: "caracol-marron-en-hoja-verde-oKhcGwGcENQ",
      ja: "緑の葉の上の茶色のカタツムリ-oKhcGwGcENQ",
      fr: "escargot-brun-sur-feuille-verte-oKhcGwGcENQ",
      it: "lumaca-marrone-su-foglia-verde-oKhcGwGcENQ",
      ko: "녹색-잎에-갈색-달팽이-oKhcGwGcENQ",
      de: "braune-schnecke-auf-grunem-blatt-oKhcGwGcENQ",
      pt: "caracol-marrom-na-folha-verde-oKhcGwGcENQ",
      id: "siput-coklat-di-daun-hijau-oKhcGwGcENQ",
    },
    created_at: "2020-08-06T10:13:50Z",
    updated_at: "2025-09-05T10:11:38Z",
    promoted_at: null,
    width: 3648,
    height: 4560,
    color: "#26260c",
    blur_hash: "LA9@g=xpE4RR9J%JWBR,07IY%0j]",
    description: null,
    alt_description: "brown snail on green leaf",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1596708635238-aab8d249a455?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1596708635238-aab8d249a455?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1596708635238-aab8d249a455?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1596708635238-aab8d249a455?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1596708635238-aab8d249a455?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1596708635238-aab8d249a455",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-snail-on-green-leaf-oKhcGwGcENQ",
      html: "https://unsplash.com/photos/brown-snail-on-green-leaf-oKhcGwGcENQ",
      download:
        "https://unsplash.com/photos/oKhcGwGcENQ/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
      download_location:
        "https://api.unsplash.com/photos/oKhcGwGcENQ/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
    },
    likes: 70,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "c1F3AlctvqE",
      updated_at: "2024-10-31T04:29:18Z",
      username: "joaocscosta",
      name: "João Costa",
      first_name: "João",
      last_name: "Costa",
      twitter_username: "joaocscosta",
      portfolio_url: null,
      bio: null,
      location: "Portugal",
      instagram_username: "joaocscosta",
      total_collections: 0,
      total_likes: 1,
      total_photos: 18,
    },
  },
  {
    id: "f6DgIqdayMk",
    slug: "brown-snail-on-brown-tree-trunk-f6DgIqdayMk",
    alternative_slugs: {
      en: "brown-snail-on-brown-tree-trunk-f6DgIqdayMk",
      es: "caracol-marron-en-tronco-de-arbol-marron-f6DgIqdayMk",
      ja: "茶色の木の幹の上の茶色のカタツムリ-f6DgIqdayMk",
      fr: "escargot-brun-sur-tronc-darbre-brun-f6DgIqdayMk",
      it: "lumaca-marrone-su-tronco-dalbero-marrone-f6DgIqdayMk",
      ko: "갈색-나무-줄기에-갈색-달팽이-f6DgIqdayMk",
      de: "braune-schnecke-am-braunen-baumstamm-f6DgIqdayMk",
      pt: "caracol-marrom-no-tronco-marrom-da-arvore-f6DgIqdayMk",
      id: "siput-coklat-di-batang-pohon-coklat-f6DgIqdayMk",
    },
    created_at: "2020-09-28T08:36:53Z",
    updated_at: "2025-09-05T09:53:15Z",
    promoted_at: null,
    width: 2720,
    height: 3808,
    color: "#262640",
    blur_hash: "LKBgh*_KIAIDprb;Vti~8|D+WBtN",
    description: null,
    alt_description: "brown snail on brown tree trunk",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1601282185257-f80be4419f6c?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1601282185257-f80be4419f6c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1601282185257-f80be4419f6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1601282185257-f80be4419f6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1601282185257-f80be4419f6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1601282185257-f80be4419f6c",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-snail-on-brown-tree-trunk-f6DgIqdayMk",
      html: "https://unsplash.com/photos/brown-snail-on-brown-tree-trunk-f6DgIqdayMk",
      download:
        "https://unsplash.com/photos/f6DgIqdayMk/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
      download_location:
        "https://api.unsplash.com/photos/f6DgIqdayMk/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
    },
    likes: 81,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "QsdGLe2nU2Y",
      updated_at: "2025-02-12T01:17:23Z",
      username: "alexxsvch",
      name: "Alexey Savchenko",
      first_name: "Alexey",
      last_name: "Savchenko",
      twitter_username: "Alex_Svch",
      portfolio_url: null,
      bio: null,
      location: "Kiev, Ukraine",
      links: [Object],
      profile_image: [Object],
      instagram_username: "alexxsvch",
      total_collections: 0,
      total_likes: 26,
      total_photos: 89,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: [Object],
    },
  },
  {
    id: "Bgw_p_Sze4A",
    slug: "closeup-photography-of-brown-snail-Bgw_p_Sze4A",
    alternative_slugs: {
      en: "closeup-photography-of-brown-snail-Bgw_p_Sze4A",
      es: "fotografia-de-primer-plano-del-caracol-marron-Bgw_p_Sze4A",
      ja: "茶色のカタツムリのクローズアップ写真-Bgw_p_Sze4A",
      fr: "photographie-en-gros-plan-descargot-brun-Bgw_p_Sze4A",
      it: "fotografia-ravvicinata-di-lumaca-marrone-Bgw_p_Sze4A",
      ko: "갈색-달팽이의-근접-촬영-Bgw_p_Sze4A",
      de: "nahaufnahme-der-braunen-schnecke-Bgw_p_Sze4A",
      pt: "fotografia-closeup-de-caracol-marrom-Bgw_p_Sze4A",
      id: "fotografi-closeup-siput-coklat-Bgw_p_Sze4A",
    },
    created_at: "2019-09-26T21:55:07Z",
    updated_at: "2025-09-05T10:47:45Z",
    promoted_at: null,
    width: 4000,
    height: 3000,
    color: "#d9d9d9",
    blur_hash: "LMKdi2Mxxu-;~WaKMxtR~q-;f5WC",
    description: "Snail 🐌 ",
    alt_description: "closeup photography of brown snail",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1569534893984-48aec815679b?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1569534893984-48aec815679b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1569534893984-48aec815679b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1569534893984-48aec815679b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1569534893984-48aec815679b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1569534893984-48aec815679b",
    },
    links: {
      self: "https://api.unsplash.com/photos/closeup-photography-of-brown-snail-Bgw_p_Sze4A",
      html: "https://unsplash.com/photos/closeup-photography-of-brown-snail-Bgw_p_Sze4A",
      download:
        "https://unsplash.com/photos/Bgw_p_Sze4A/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
      download_location:
        "https://api.unsplash.com/photos/Bgw_p_Sze4A/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxzbmFpbHxlbnwwfHx8fDE3NTcwNjk3NzF8MA",
    },
    likes: 95,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: { wallpapers: [Object], nature: [Object] },
    asset_type: "photo",
    user: {
      id: "oK4acxIDEtk",
      updated_at: "2025-09-03T10:54:24Z",
      username: "joshuakettle",
      name: "Joshua Kettle",
      first_name: "Joshua Kettle",
      last_name: null,
      twitter_username: null,
      portfolio_url: "https://joshuakettle.com",
      bio: "hi, I'm a travel and landscape photographer from Germany :)",
      location: "Germany",
      links: [Object],
      profile_image: [Object],
      instagram_username: "joshuakettle.photography",
      total_collections: 23,
      total_likes: 187,
      total_photos: 947,
      total_promoted_photos: 160,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: [Object],
    },
  },
  {
    id: "NWWUM76NuGU",
    slug: "brown-snail-on-brown-wooden-stick-NWWUM76NuGU",
    alternative_slugs: {
      en: "brown-snail-on-brown-wooden-stick-NWWUM76NuGU",
      es: "caracol-marron-en-palo-de-madera-marron-NWWUM76NuGU",
      ja: "茶色の木の棒に茶色のカタツムリ-NWWUM76NuGU",
      fr: "escargot-brun-sur-baton-en-bois-brun-NWWUM76NuGU",
      it: "lumaca-marrone-su-bastone-di-legno-marrone-NWWUM76NuGU",
      ko: "갈색-나무-막대기에-갈색-달팽이-NWWUM76NuGU",
      de: "braune-schnecke-auf-braunem-holzstab-NWWUM76NuGU",
      pt: "caracol-marrom-na-vara-de-madeira-marrom-NWWUM76NuGU",
      id: "siput-coklat-pada-tongkat-kayu-coklat-NWWUM76NuGU",
    },
    created_at: "2020-11-12T18:57:35Z",
    updated_at: "2025-09-05T06:03:10Z",
    promoted_at: null,
    width: 5213,
    height: 3712,
    color: "#26260c",
    blur_hash: "L5A0aN-V4:0MIybK%FE200jvs;xZ",
    description: null,
    alt_description: "brown snail on brown wooden stick",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1605207440380-708d13e10373?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8c25haWx8ZW58MHx8fHwxNzU3MDY5NzcxfDA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1605207440380-708d13e10373?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8c25haWx8ZW58MHx8fHwxNzU3MDY5NzcxfDA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1605207440380-708d13e10373?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8c25haWx8ZW58MHx8fHwxNzU3MDY5NzcxfDA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1605207440380-708d13e10373?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8c25haWx8ZW58MHx8fHwxNzU3MDY5NzcxfDA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1605207440380-708d13e10373?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8c25haWx8ZW58MHx8fHwxNzU3MDY5NzcxfDA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1605207440380-708d13e10373",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-snail-on-brown-wooden-stick-NWWUM76NuGU",
      html: "https://unsplash.com/photos/brown-snail-on-brown-wooden-stick-NWWUM76NuGU",
      download:
        "https://unsplash.com/photos/NWWUM76NuGU/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8c25haWx8ZW58MHx8fHwxNzU3MDY5NzcxfDA",
      download_location:
        "https://api.unsplash.com/photos/NWWUM76NuGU/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8c25haWx8ZW58MHx8fHwxNzU3MDY5NzcxfDA",
    },
    likes: 101,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: { animals: [Object] },
    asset_type: "photo",
    user: {
      id: "Vw1vSqNowLQ",
      updated_at: "2025-06-04T01:23:42Z",
      username: "alexas_fotos",
      name: "Alexas_Fotos",
      first_name: "Alexas_Fotos",
      last_name: null,
      twitter_username: null,
      portfolio_url: "https://paypal.me/AlexaSt?locale.x=de_DE",
      bio:
        "A life without animals is not worth living for me. Animal protection is very important to me.\r\n" +
        "I support many wild animals all year round in our garden and I also love my pets.",
      location: null,
      links: [Object],
      profile_image: [Object],
      instagram_username: null,
      total_collections: 15,
      total_likes: 377,
      total_photos: 383,
      total_promoted_photos: 0,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: [Object],
    },
  },
];
