import { env } from "$env/dynamic/private";
import { createApi } from "unsplash-js";

const serverApi = createApi({
  accessKey: env.UNSPLASH_ACCESS_KEY,
});

export { serverApi as unsplash };

export const mock = [
  {
    id: "PPagKlXwIR0",
    slug: "a-close-up-of-a-glass-door-with-the-word-hello-on-it-PPagKlXwIR0",
    alternative_slugs: {
      en: "a-close-up-of-a-glass-door-with-the-word-hello-on-it-PPagKlXwIR0",
      es: "un-primer-plano-de-una-puerta-de-vidrio-con-la-palabra-hola-PPagKlXwIR0",
      ja: "こんにちはという言葉が書かれたガラスドアのクローズアップ-PPagKlXwIR0",
      fr: "un-gros-plan-dune-porte-vitree-avec-le-mot-bonjour-dessus-PPagKlXwIR0",
      it: "un-primo-piano-di-una-porta-a-vetri-con-la-parola-ciao-su-di-esso-PPagKlXwIR0",
      ko: "안녕하세요라는-단어가-적힌-유리문의-클로즈업-PPagKlXwIR0",
      de: "eine-nahaufnahme-einer-glastur-mit-dem-wort-hallo-darauf-PPagKlXwIR0",
      pt: "um-close-up-de-uma-porta-de-vidro-com-a-palavra-ola-nela-PPagKlXwIR0",
      id: "close-up-pintu-kaca-dengan-kata-halo-di-atasnya-PPagKlXwIR0",
    },
    created_at: "2023-04-10T23:00:03Z",
    updated_at: "2025-09-04T09:33:15Z",
    promoted_at: null,
    width: 4893,
    height: 3262,
    color: "#8ca6c0",
    blur_hash: "LPF$L#DhE1xa;[tS%MjF?wR-wGof",
    description: "Hello!",
    alt_description: "a close up of a glass door with the word hello on it",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1681167547637-c519f998ae5a?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1681167547637-c519f998ae5a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1681167547637-c519f998ae5a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1681167547637-c519f998ae5a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1681167547637-c519f998ae5a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1681167547637-c519f998ae5a",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-close-up-of-a-glass-door-with-the-word-hello-on-it-PPagKlXwIR0",
      html: "https://unsplash.com/photos/a-close-up-of-a-glass-door-with-the-word-hello-on-it-PPagKlXwIR0",
      download:
        "https://unsplash.com/photos/PPagKlXwIR0/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
      download_location:
        "https://api.unsplash.com/photos/PPagKlXwIR0/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
    },
    likes: 8,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "a6drpbfb7_4",
      updated_at: "2025-07-24T14:20:21Z",
      username: "londonweddingphotographer",
      name: "Chris Boland",
      first_name: "Chris",
      last_name: "Boland",
      twitter_username: null,
      portfolio_url: "https://www.chrisboland.com/london-wedding-videographer/",
      bio: "I am a London-based wedding photographer and videographer and am in love with all types of photography.",
      location: "London",
      links: [Object],
      profile_image: [Object],
      instagram_username: null,
      total_collections: 0,
      total_likes: 9,
      total_photos: 94,
      total_promoted_photos: 0,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: [Object],
    },
  },
  {
    id: "kVcJhDg5nPw",
    slug: "a-bird-sitting-on-top-of-a-pile-of-leaves-kVcJhDg5nPw",
    alternative_slugs: {
      en: "a-bird-sitting-on-top-of-a-pile-of-leaves-kVcJhDg5nPw",
      es: "un-pajaro-sentado-encima-de-un-monton-de-hojas-kVcJhDg5nPw",
      ja: "葉っぱの山の上に座っている鳥-kVcJhDg5nPw",
      fr: "un-oiseau-assis-sur-un-tas-de-feuilles-kVcJhDg5nPw",
      it: "un-uccello-seduto-in-cima-a-un-mucchio-di-foglie-kVcJhDg5nPw",
      ko: "나뭇잎-더미-위에-앉아-있는-새-kVcJhDg5nPw",
      de: "ein-vogel-der-auf-einem-laubhaufen-sitzt-kVcJhDg5nPw",
      pt: "um-passaro-sentado-em-cima-de-uma-pilha-de-folhas-kVcJhDg5nPw",
      id: "seekor-burung-duduk-di-atas-tumpukan-daun-kVcJhDg5nPw",
    },
    created_at: "2024-11-22T13:54:37Z",
    updated_at: "2025-09-04T10:20:10Z",
    promoted_at: null,
    width: 5303,
    height: 3788,
    color: "#8c8c8c",
    blur_hash: "LUF~N.wvM{jY?wWqV@WBM{oza}ay",
    description: null,
    alt_description: "A bird sitting on top of a pile of leaves",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1732282601863-303dadf50854?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1732282601863-303dadf50854?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1732282601863-303dadf50854?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1732282601863-303dadf50854?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1732282601863-303dadf50854?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1732282601863-303dadf50854",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-bird-sitting-on-top-of-a-pile-of-leaves-kVcJhDg5nPw",
      html: "https://unsplash.com/photos/a-bird-sitting-on-top-of-a-pile-of-leaves-kVcJhDg5nPw",
      download:
        "https://unsplash.com/photos/kVcJhDg5nPw/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
      download_location:
        "https://api.unsplash.com/photos/kVcJhDg5nPw/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwyfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
    },
    likes: 0,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "XRPLspcLA5U",
      updated_at: "2025-06-18T01:20:13Z",
      username: "benjaminelliott",
      name: "Benjamin Elliott",
      first_name: "Benjamin",
      last_name: "Elliott",
      twitter_username: null,
      portfolio_url: "https://www.buymeacoffee.com/benjaminelliott",
      bio: "Hey there! Using my photographs? Tag my Instagram @benjaminjohnelliott & Buy Me A Coffee at www.buymeacoffee.com/benjaminelliott THANK YOU!!!!!",
      location: "Sheffield",
      links: [Object],
      profile_image: [Object],
      instagram_username: "benjaminjohnelliott",
      total_collections: 23,
      total_likes: 15,
      total_photos: 896,
      total_promoted_photos: 27,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: [Object],
    },
  },
  {
    id: "HpCahYbtJ_Y",
    slug: "yellow-and-black-wooden-signage-HpCahYbtJ_Y",
    alternative_slugs: {
      en: "yellow-and-black-wooden-signage-HpCahYbtJ_Y",
      es: "senalizacion-de-madera-amarilla-y-negra-HpCahYbtJ_Y",
      ja: "黄色と黒の木製看板-HpCahYbtJ_Y",
      fr: "signaletique-en-bois-jaune-et-noir-HpCahYbtJ_Y",
      it: "segnaletica-in-legno-gialla-e-nera-HpCahYbtJ_Y",
      ko: "노란색과-검은-색-나무-간판-HpCahYbtJ_Y",
      de: "gelbe-und-schwarze-holzbeschilderung-HpCahYbtJ_Y",
      pt: "sinalizacao-de-madeira-amarela-e-preta-HpCahYbtJ_Y",
      id: "papan-nama-kayu-kuning-dan-hitam-HpCahYbtJ_Y",
    },
    created_at: "2021-08-07T09:10:06Z",
    updated_at: "2025-09-04T09:26:14Z",
    promoted_at: null,
    width: 5472,
    height: 3648,
    color: "#262626",
    blur_hash: "LGF~1|xa1St6~Ws,^%ofMLsl=pWW",
    description: null,
    alt_description: "yellow and black wooden signage",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1628327387796-49d98095cf32?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1628327387796-49d98095cf32?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1628327387796-49d98095cf32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1628327387796-49d98095cf32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1628327387796-49d98095cf32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1628327387796-49d98095cf32",
    },
    links: {
      self: "https://api.unsplash.com/photos/yellow-and-black-wooden-signage-HpCahYbtJ_Y",
      html: "https://unsplash.com/photos/yellow-and-black-wooden-signage-HpCahYbtJ_Y",
      download:
        "https://unsplash.com/photos/HpCahYbtJ_Y/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
      download_location:
        "https://api.unsplash.com/photos/HpCahYbtJ_Y/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwzfHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
    },
    likes: 16,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "Uneml_yNJZE",
      updated_at: "2025-09-03T22:35:26Z",
      username: "reganography",
      name: "Samuel Regan-Asante",
      first_name: "Samuel",
      last_name: "Regan-Asante",
      twitter_username: "fkaregan",
      portfolio_url: "https://reganography.com/",
      bio: "Former child.",
      location: "London",
      links: [Object],
      profile_image: [Object],
      instagram_username: "reganography",
      total_collections: 3,
      total_likes: 413,
      total_photos: 1380,
      total_promoted_photos: 172,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: [Object],
    },
  },
  {
    id: "FuR8dwF4uxc",
    slug: "a-black-door-handle-on-a-blue-wall-FuR8dwF4uxc",
    alternative_slugs: {
      en: "a-black-door-handle-on-a-blue-wall-FuR8dwF4uxc",
      es: "una-manija-de-puerta-negra-en-una-pared-azul-FuR8dwF4uxc",
      ja: "青い壁に黒いドアハンドル-FuR8dwF4uxc",
      fr: "une-poignee-de-porte-noire-sur-un-mur-bleu-FuR8dwF4uxc",
      it: "una-maniglia-nera-della-porta-su-una-parete-blu-FuR8dwF4uxc",
      ko: "파란색-벽에-검은색-문-손잡이-FuR8dwF4uxc",
      de: "ein-schwarzer-turgriff-an-einer-blauen-wand-FuR8dwF4uxc",
      pt: "uma-macaneta-de-porta-preta-em-uma-parede-azul-FuR8dwF4uxc",
      id: "pegangan-pintu-hitam-di-dinding-biru-FuR8dwF4uxc",
    },
    created_at: "2023-06-02T21:26:38Z",
    updated_at: "2025-09-04T07:23:17Z",
    promoted_at: null,
    width: 3538,
    height: 5307,
    color: "#c0f3f3",
    blur_hash: "LRJANI0#4ot8NGi^t6WAozVstRRj",
    description: null,
    alt_description: "a black door handle on a blue wall",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1685741149700-1c4e6403c7bb?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1685741149700-1c4e6403c7bb?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1685741149700-1c4e6403c7bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1685741149700-1c4e6403c7bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1685741149700-1c4e6403c7bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1685741149700-1c4e6403c7bb",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-black-door-handle-on-a-blue-wall-FuR8dwF4uxc",
      html: "https://unsplash.com/photos/a-black-door-handle-on-a-blue-wall-FuR8dwF4uxc",
      download:
        "https://unsplash.com/photos/FuR8dwF4uxc/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
      download_location:
        "https://api.unsplash.com/photos/FuR8dwF4uxc/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw0fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
    },
    likes: 19,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: { monochromatic: [Object] },
    asset_type: "photo",
    user: {
      id: "C9oVQA7jNEs",
      updated_at: "2025-08-31T19:58:08Z",
      username: "pratophoto",
      name: "Brayden Prato",
      first_name: "Brayden",
      last_name: "Prato",
      twitter_username: null,
      portfolio_url: "http://www.pratophoto.ca",
      bio: null,
      location: "Okanagan, BC",
      links: [Object],
      profile_image: [Object],
      instagram_username: "pratophoto",
      total_collections: 8,
      total_likes: 4,
      total_photos: 151,
      total_promoted_photos: 32,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: [Object],
    },
  },
  {
    id: "GRZYAxRTE78",
    slug: "a-close-up-of-a-black-cow-in-a-field-GRZYAxRTE78",
    alternative_slugs: {
      en: "a-close-up-of-a-black-cow-in-a-field-GRZYAxRTE78",
      es: "un-primer-plano-de-una-vaca-negra-en-un-campo-GRZYAxRTE78",
      ja: "野原の黒い牛の接写-GRZYAxRTE78",
      fr: "gros-plan-dune-vache-noire-dans-un-champ-GRZYAxRTE78",
      it: "un-primo-piano-di-una-mucca-nera-in-un-campo-GRZYAxRTE78",
      ko: "들판에서-검은-암소의-클로즈업-GRZYAxRTE78",
      de: "nahaufnahme-einer-schwarzen-kuh-auf-einem-feld-GRZYAxRTE78",
      pt: "um-close-up-de-uma-vaca-negra-em-um-campo-GRZYAxRTE78",
      id: "close-up-sapi-hitam-di-ladang-GRZYAxRTE78",
    },
    created_at: "2021-11-01T16:23:14Z",
    updated_at: "2025-09-04T09:35:22Z",
    promoted_at: null,
    width: 4096,
    height: 3072,
    color: "#f3f3f3",
    blur_hash: "L.HLeva#t3j[~qfkWCaz?coeWDay",
    description: null,
    alt_description: "a close up of a black cow in a field",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1635783398836-d6c4e1e98aa9?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1635783398836-d6c4e1e98aa9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1635783398836-d6c4e1e98aa9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1635783398836-d6c4e1e98aa9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1635783398836-d6c4e1e98aa9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1635783398836-d6c4e1e98aa9",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-close-up-of-a-black-cow-in-a-field-GRZYAxRTE78",
      html: "https://unsplash.com/photos/a-close-up-of-a-black-cow-in-a-field-GRZYAxRTE78",
      download:
        "https://unsplash.com/photos/GRZYAxRTE78/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
      download_location:
        "https://api.unsplash.com/photos/GRZYAxRTE78/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw1fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
    },
    likes: 7,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "LPyYAcC_xPU",
      updated_at: "2025-08-28T17:45:00Z",
      username: "lucygreen2",
      name: "Lucy Green",
      first_name: "Lucy",
      last_name: "Green",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: null,
      links: [Object],
      profile_image: [Object],
      instagram_username: null,
      total_collections: 0,
      total_likes: 1,
      total_photos: 49,
      total_promoted_photos: 0,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: [Object],
    },
  },
  {
    id: "jy5Rdca-IeI",
    slug: "black-and-red-bird-on-tree-branch-during-daytime-jy5Rdca-IeI",
    alternative_slugs: {
      en: "black-and-red-bird-on-tree-branch-during-daytime-jy5Rdca-IeI",
      es: "pajaro-negro-y-rojo-en-la-rama-de-un-arbol-durante-el-dia-jy5Rdca-IeI",
      ja: "昼間木の枝にとまる黒と赤の鳥-jy5Rdca-IeI",
      fr: "oiseau-noir-et-rouge-sur-la-branche-darbre-pendant-la-journee-jy5Rdca-IeI",
      it: "uccello-nero-e-rosso-sul-ramo-dellalbero-durante-il-giorno-jy5Rdca-IeI",
      ko: "낮-동안-나뭇가지에-검은-색과-붉은-새-jy5Rdca-IeI",
      de: "schwarzer-und-roter-vogel-tagsuber-am-ast-jy5Rdca-IeI",
      pt: "passaro-preto-e-vermelho-no-galho-da-arvore-durante-o-dia-jy5Rdca-IeI",
      id: "burung-hitam-dan-merah-di-cabang-pohon-pada-siang-hari-jy5Rdca-IeI",
    },
    created_at: "2021-05-22T23:44:41Z",
    updated_at: "2025-09-04T10:06:17Z",
    promoted_at: null,
    width: 6000,
    height: 4000,
    color: "#405940",
    blur_hash: "L68q$dxt4WD+?tRkM{tPIDWDt5xt",
    description: null,
    alt_description: "black and red bird on tree branch during daytime",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1621726742364-78c74f1bc56f?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1621726742364-78c74f1bc56f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1621726742364-78c74f1bc56f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1621726742364-78c74f1bc56f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1621726742364-78c74f1bc56f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1621726742364-78c74f1bc56f",
    },
    links: {
      self: "https://api.unsplash.com/photos/black-and-red-bird-on-tree-branch-during-daytime-jy5Rdca-IeI",
      html: "https://unsplash.com/photos/black-and-red-bird-on-tree-branch-during-daytime-jy5Rdca-IeI",
      download:
        "https://unsplash.com/photos/jy5Rdca-IeI/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
      download_location:
        "https://api.unsplash.com/photos/jy5Rdca-IeI/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw2fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
    },
    likes: 0,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "q4mk4I-wLv4",
      updated_at: "2024-10-10T21:40:06Z",
      username: "stluhdog",
      name: "LR HULTS",
      first_name: "LR",
      last_name: "HULTS",
      twitter_username: null,
      portfolio_url: "http://anoldguywhoknowsshit.com",
      bio: null,
      location: "Midwest",
      links: [Object],
      profile_image: [Object],
      instagram_username: null,
      total_collections: 10,
      total_likes: 0,
      total_photos: 130,
      total_promoted_photos: 0,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: [Object],
    },
  },
  {
    id: "CbeFxZ8xcwg",
    slug: "a-neon-sign-that-says-hello-on-a-wall-CbeFxZ8xcwg",
    alternative_slugs: {
      en: "a-neon-sign-that-says-hello-on-a-wall-CbeFxZ8xcwg",
      es: "un-letrero-de-neon-que-dice-hola-en-una-pared-CbeFxZ8xcwg",
      ja: "壁にこんにちはと書かれたネオンサイン-CbeFxZ8xcwg",
      fr: "une-enseigne-au-neon-qui-dit-bonjour-sur-un-mur-CbeFxZ8xcwg",
      it: "uninsegna-al-neon-che-dice-ciao-su-un-muro-CbeFxZ8xcwg",
      ko: "벽에-인사하는-네온사인-CbeFxZ8xcwg",
      de: "eine-leuchtreklame-die-an-einer-wand-hallo-sagt-CbeFxZ8xcwg",
      pt: "um-letreiro-de-neon-que-diz-ola-em-uma-parede-CbeFxZ8xcwg",
      id: "tanda-neon-yang-mengatakan-halo-di-dinding-CbeFxZ8xcwg",
    },
    created_at: "2024-02-23T09:01:32Z",
    updated_at: "2025-09-04T09:39:30Z",
    promoted_at: null,
    width: 4160,
    height: 6240,
    color: "#262626",
    blur_hash: "LBAcuaR,56Ip?HV?NGWC0yIU?Ht6",
    description: null,
    alt_description: "a neon sign that says hello on a wall",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1708678310765-65ff0b30068f?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1708678310765-65ff0b30068f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1708678310765-65ff0b30068f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1708678310765-65ff0b30068f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1708678310765-65ff0b30068f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1708678310765-65ff0b30068f",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-neon-sign-that-says-hello-on-a-wall-CbeFxZ8xcwg",
      html: "https://unsplash.com/photos/a-neon-sign-that-says-hello-on-a-wall-CbeFxZ8xcwg",
      download:
        "https://unsplash.com/photos/CbeFxZ8xcwg/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
      download_location:
        "https://api.unsplash.com/photos/CbeFxZ8xcwg/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw3fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
    },
    likes: 6,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "Li4pTZbYt-0",
      updated_at: "2024-07-31T02:03:51Z",
      username: "baguette_knight",
      name: "Baguette Knight",
      first_name: "Baguette",
      last_name: "Knight",
      twitter_username: null,
      portfolio_url: null,
      bio: "I take picture on the street so you don't have to",
      location: null,
      links: [Object],
      profile_image: [Object],
      instagram_username: "pseudoughnut",
      total_collections: 0,
      total_likes: 2,
      total_photos: 112,
      total_promoted_photos: 0,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: [Object],
    },
  },
  {
    id: "Ym6sfQFxOho",
    slug: "a-person-holding-up-a-sticker-with-the-word-hello-on-it-Ym6sfQFxOho",
    alternative_slugs: {
      en: "a-person-holding-up-a-sticker-with-the-word-hello-on-it-Ym6sfQFxOho",
      es: "una-persona-sosteniendo-una-pegatina-con-la-palabra-hola-Ym6sfQFxOho",
      ja: "こんにちはと書かれたステッカーを掲げる人-Ym6sfQFxOho",
      fr: "une-personne-tenant-un-autocollant-avec-le-mot-bonjour-dessus-Ym6sfQFxOho",
      it: "una-persona-che-regge-un-adesivo-con-la-parola-ciao-su-di-esso-Ym6sfQFxOho",
      ko: "안녕하세요라는-단어가-적힌-스티커를-들고-있는-사람-Ym6sfQFxOho",
      de: "eine-person-die-einen-aufkleber-mit-dem-wort-hallo-hochhalt-Ym6sfQFxOho",
      pt: "uma-pessoa-segurando-um-adesivo-com-a-palavra-ola-nele-Ym6sfQFxOho",
      id: "seseorang-memegang-stiker-dengan-kata-halo-di-atasnya-Ym6sfQFxOho",
    },
    created_at: "2021-10-11T21:59:30Z",
    updated_at: "2025-09-04T09:12:35Z",
    promoted_at: null,
    width: 6016,
    height: 4016,
    color: "#262626",
    blur_hash: "LDEfA_DN4m?HXT%gIo4nE*I;IAt7",
    description: null,
    alt_description: "a person holding up a sticker with the word hello on it",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1633989464004-1aada5ed6702?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1633989464004-1aada5ed6702?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1633989464004-1aada5ed6702?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1633989464004-1aada5ed6702?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1633989464004-1aada5ed6702?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1633989464004-1aada5ed6702",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-person-holding-up-a-sticker-with-the-word-hello-on-it-Ym6sfQFxOho",
      html: "https://unsplash.com/photos/a-person-holding-up-a-sticker-with-the-word-hello-on-it-Ym6sfQFxOho",
      download:
        "https://unsplash.com/photos/Ym6sfQFxOho/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
      download_location:
        "https://api.unsplash.com/photos/Ym6sfQFxOho/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw4fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
    },
    likes: 30,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "GcO9dn8WwnY",
      updated_at: "2025-08-14T09:57:06Z",
      username: "lemonvlad",
      name: "Vladislav Klapin",
      first_name: "Vladislav",
      last_name: "Klapin",
      twitter_username: null,
      portfolio_url: null,
      bio: "Hey! Show your appreciation by donating. Thank you!",
      location: "Latvia",
      links: [Object],
      profile_image: [Object],
      instagram_username: "lemonvlad",
      total_collections: 0,
      total_likes: 24,
      total_photos: 21,
      total_promoted_photos: 3,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: [Object],
    },
  },
  {
    id: "iY6QMkP66mI",
    slug: "black-hello-text-decor-iY6QMkP66mI",
    alternative_slugs: {
      en: "black-hello-text-decor-iY6QMkP66mI",
      es: "negro-decoracion-de-texto-hola-iY6QMkP66mI",
      ja: "黒のハローテキストデコレーション-iY6QMkP66mI",
      fr: "decor-de-texte-hello-noir-iY6QMkP66mI",
      it: "decorazione-con-testo-hello-nero-iY6QMkP66mI",
      ko: "블랙-헬로-텍스트-데코-iY6QMkP66mI",
      de: "schwarz-hello-textdekor-iY6QMkP66mI",
      pt: "decoracao-de-texto-ola-preto-iY6QMkP66mI",
      id: "hitam-halo-dekorasi-teks-iY6QMkP66mI",
    },
    created_at: "2019-09-10T19:44:20Z",
    updated_at: "2025-09-04T07:02:55Z",
    promoted_at: null,
    width: 6000,
    height: 4000,
    color: "#262626",
    blur_hash: "LsF$n]NYogaePqs*WBWp=|X9axof",
    description: "Lettering",
    alt_description: "black Hello text decor",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1568144628871-ccbb00fc297c?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1568144628871-ccbb00fc297c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1568144628871-ccbb00fc297c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1568144628871-ccbb00fc297c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1568144628871-ccbb00fc297c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1568144628871-ccbb00fc297c",
    },
    links: {
      self: "https://api.unsplash.com/photos/black-hello-text-decor-iY6QMkP66mI",
      html: "https://unsplash.com/photos/black-hello-text-decor-iY6QMkP66mI",
      download:
        "https://unsplash.com/photos/iY6QMkP66mI/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
      download_location:
        "https://api.unsplash.com/photos/iY6QMkP66mI/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHw5fHxoZWxsbyUyMXxlbnwwfHx8fDE3NTY5ODcwNzl8MA",
    },
    likes: 193,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "lswtqAA4yg4",
      updated_at: "2025-07-30T01:18:10Z",
      username: "octadan",
      name: "Octavian-Dan Craciun",
      first_name: "Octavian-Dan",
      last_name: "Craciun",
      twitter_username: null,
      portfolio_url: "https://cutt.ly/dMVLG2L",
      bio: null,
      location: "Munich",
      links: [Object],
      profile_image: [Object],
      instagram_username: null,
      total_collections: 6,
      total_likes: 27,
      total_photos: 145,
      total_promoted_photos: 5,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: [Object],
    },
  },
  {
    id: "iWFwJyKqgFg",
    slug: "a-group-of-people-standing-next-to-each-other-iWFwJyKqgFg",
    alternative_slugs: {
      en: "a-group-of-people-standing-next-to-each-other-iWFwJyKqgFg",
      es: "un-grupo-de-personas-de-pie-una-al-lado-de-la-otra-iWFwJyKqgFg",
      ja: "隣り合って立っている人々のグループ-iWFwJyKqgFg",
      fr: "un-groupe-de-personnes-debout-les-unes-a-cote-des-autres-iWFwJyKqgFg",
      it: "un-gruppo-di-persone-in-piedi-luna-accanto-allaltra-iWFwJyKqgFg",
      ko: "나란히-서-있는-한-무리의-사람들-iWFwJyKqgFg",
      de: "eine-gruppe-von-menschen-die-nebeneinander-stehen-iWFwJyKqgFg",
      pt: "um-grupo-de-pessoas-em-pe-um-ao-lado-do-outro-iWFwJyKqgFg",
      id: "sekelompok-orang-berdiri-bersebelahan-iWFwJyKqgFg",
    },
    created_at: "2024-11-28T10:02:05Z",
    updated_at: "2025-09-04T07:41:41Z",
    promoted_at: null,
    width: 4671,
    height: 6229,
    color: "#c0c0c0",
    blur_hash: "LNF6a{~qITRjIA.8kDD%_2tSxvIU",
    description: "Hello Friend",
    alt_description: "A group of people standing next to each other",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1732788122021-d9c2c4f78adc?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8aGVsbG8lMjF8ZW58MHx8fHwxNzU2OTg3MDc5fDA&ixlib=rb-4.1.0",
      full: "https://images.unsplash.com/photo-1732788122021-d9c2c4f78adc?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8aGVsbG8lMjF8ZW58MHx8fHwxNzU2OTg3MDc5fDA&ixlib=rb-4.1.0&q=85",
      regular:
        "https://images.unsplash.com/photo-1732788122021-d9c2c4f78adc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8aGVsbG8lMjF8ZW58MHx8fHwxNzU2OTg3MDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1732788122021-d9c2c4f78adc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8aGVsbG8lMjF8ZW58MHx8fHwxNzU2OTg3MDc5fDA&ixlib=rb-4.1.0&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1732788122021-d9c2c4f78adc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8aGVsbG8lMjF8ZW58MHx8fHwxNzU2OTg3MDc5fDA&ixlib=rb-4.1.0&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1732788122021-d9c2c4f78adc",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-group-of-people-standing-next-to-each-other-iWFwJyKqgFg",
      html: "https://unsplash.com/photos/a-group-of-people-standing-next-to-each-other-iWFwJyKqgFg",
      download:
        "https://unsplash.com/photos/iWFwJyKqgFg/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8aGVsbG8lMjF8ZW58MHx8fHwxNzU2OTg3MDc5fDA",
      download_location:
        "https://api.unsplash.com/photos/iWFwJyKqgFg/download?ixid=M3w3OTY4MzF8MHwxfHNlYXJjaHwxMHx8aGVsbG8lMjF8ZW58MHx8fHwxNzU2OTg3MDc5fDA",
    },
    likes: 1,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "fMv9eEj_rgY",
      updated_at: "2025-01-13T09:45:50Z",
      username: "svenqing",
      name: "Xuewen Qing",
      first_name: "Xuewen",
      last_name: "Qing",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: null,
      links: [Object],
      profile_image: [Object],
      instagram_username: null,
      total_collections: 0,
      total_likes: 2,
      total_photos: 15,
      total_promoted_photos: 0,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: [Object],
    },
  },
];
